//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestingWebServer.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://edu.softserve.com/", ConfigurationName="ServiceReference.ICommon")]
    public interface ICommon {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetCoolDownTime", ReplyAction="*")]
        TestingWebServer.ServiceReference.setCoolDownTimeResponse setCoolDownTime(TestingWebServer.ServiceReference.setCoolDownTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetCoolDownTime", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setCoolDownTimeResponse> setCoolDownTimeAsync(TestingWebServer.ServiceReference.setCoolDownTime request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetTokenLifeTime", ReplyAction="*")]
        TestingWebServer.ServiceReference.setTokenLifeTimeResponse setTokenLifeTime(TestingWebServer.ServiceReference.setTokenLifeTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:SetTokenLifeTime", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setTokenLifeTimeResponse> setTokenLifeTimeAsync(TestingWebServer.ServiceReference.setTokenLifeTime request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetAllUsers", ReplyAction="*")]
        TestingWebServer.ServiceReference.getAllUsersResponse getAllUsers(TestingWebServer.ServiceReference.getAllUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllUsersResponse> getAllUsersAsync(TestingWebServer.ServiceReference.getAllUsers request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetAllItems", ReplyAction="*")]
        TestingWebServer.ServiceReference.getAllItemsResponse getAllItems(TestingWebServer.ServiceReference.getAllItems request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetAllItems", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllItemsResponse> getAllItemsAsync(TestingWebServer.ServiceReference.getAllItems request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetTokenLifeTime", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestingWebServer.ServiceReference.getTokenLifeTimeResponse getTokenLifeTime(TestingWebServer.ServiceReference.getTokenLifeTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetTokenLifeTime", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getTokenLifeTimeResponse> getTokenLifeTimeAsync(TestingWebServer.ServiceReference.getTokenLifeTime request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateItem", ReplyAction="*")]
        TestingWebServer.ServiceReference.updateItemResponse updateItem(TestingWebServer.ServiceReference.updateItem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UpdateItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.updateItemResponse> updateItemAsync(TestingWebServer.ServiceReference.updateItem request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChangePassword", ReplyAction="*")]
        TestingWebServer.ServiceReference.changePasswordResponse changePassword(TestingWebServer.ServiceReference.changePassword request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.changePasswordResponse> changePasswordAsync(TestingWebServer.ServiceReference.changePassword request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login", ReplyAction="*")]
        TestingWebServer.ServiceReference.loginResponse login(TestingWebServer.ServiceReference.login request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Login", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.loginResponse> loginAsync(TestingWebServer.ServiceReference.login request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:Logout", ReplyAction="*")]
        TestingWebServer.ServiceReference.logoutResponse logout(TestingWebServer.ServiceReference.logout request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Logout", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.logoutResponse> logoutAsync(TestingWebServer.ServiceReference.logout request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddItem", ReplyAction="*")]
        TestingWebServer.ServiceReference.addItemResponse addItem(TestingWebServer.ServiceReference.addItem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AddItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.addItemResponse> addItemAsync(TestingWebServer.ServiceReference.addItem request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:DeleteItem", ReplyAction="*")]
        TestingWebServer.ServiceReference.deleteItemResponse deleteItem(TestingWebServer.ServiceReference.deleteItem request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:DeleteItem", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.deleteItemResponse> deleteItemAsync(TestingWebServer.ServiceReference.deleteItem request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:RemoveUser", ReplyAction="*")]
        TestingWebServer.ServiceReference.removeUserResponse removeUser(TestingWebServer.ServiceReference.removeUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:RemoveUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.removeUserResponse> removeUserAsync(TestingWebServer.ServiceReference.removeUser request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:CreateUser", ReplyAction="*")]
        TestingWebServer.ServiceReference.createUserResponse createUser(TestingWebServer.ServiceReference.createUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.createUserResponse> createUserAsync(TestingWebServer.ServiceReference.createUser request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:LockUser", ReplyAction="*")]
        TestingWebServer.ServiceReference.lockUserResponse lockUser(TestingWebServer.ServiceReference.lockUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:LockUser", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.lockUserResponse> lockUserAsync(TestingWebServer.ServiceReference.lockUser request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetUserName", ReplyAction="*")]
        TestingWebServer.ServiceReference.getUserNameResponse getUserName(TestingWebServer.ServiceReference.getUserName request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getUserNameResponse> getUserNameAsync(TestingWebServer.ServiceReference.getUserName request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://edu.softserve.com/)
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetCoolDownTime", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        TestingWebServer.ServiceReference.getCoolDownTimeResponse getCoolDownTime(TestingWebServer.ServiceReference.getCoolDownTime request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:GetCoolDownTime", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getCoolDownTimeResponse> getCoolDownTimeAsync(TestingWebServer.ServiceReference.getCoolDownTime request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="urn:UnlockUsers", ReplyAction="*")]
        TestingWebServer.ServiceReference.unlockUsersResponse unlockUsers(TestingWebServer.ServiceReference.unlockUsers request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:UnlockUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.unlockUsersResponse> unlockUsersAsync(TestingWebServer.ServiceReference.unlockUsers request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCoolDownTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCoolDownTime", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.setCoolDownTimeBody Body;
        
        public setCoolDownTime() {
        }
        
        public setCoolDownTime(TestingWebServer.ServiceReference.setCoolDownTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setCoolDownTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long arg1;
        
        public setCoolDownTimeBody() {
        }
        
        public setCoolDownTimeBody(string arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setCoolDownTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setCoolDownTimeResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.setCoolDownTimeResponseBody Body;
        
        public setCoolDownTimeResponse() {
        }
        
        public setCoolDownTimeResponse(TestingWebServer.ServiceReference.setCoolDownTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setCoolDownTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public setCoolDownTimeResponseBody() {
        }
        
        public setCoolDownTimeResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setTokenLifeTime {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setTokenLifeTime", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.setTokenLifeTimeBody Body;
        
        public setTokenLifeTime() {
        }
        
        public setTokenLifeTime(TestingWebServer.ServiceReference.setTokenLifeTimeBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setTokenLifeTimeBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long arg1;
        
        public setTokenLifeTimeBody() {
        }
        
        public setTokenLifeTimeBody(string arg0, long arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setTokenLifeTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="setTokenLifeTimeResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.setTokenLifeTimeResponseBody Body;
        
        public setTokenLifeTimeResponse() {
        }
        
        public setTokenLifeTimeResponse(TestingWebServer.ServiceReference.setTokenLifeTimeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class setTokenLifeTimeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public setTokenLifeTimeResponseBody() {
        }
        
        public setTokenLifeTimeResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllUsers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllUsers", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getAllUsersBody Body;
        
        public getAllUsers() {
        }
        
        public getAllUsers(TestingWebServer.ServiceReference.getAllUsersBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllUsersBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getAllUsersBody() {
        }
        
        public getAllUsersBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllUsersResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getAllUsersResponseBody Body;
        
        public getAllUsersResponse() {
        }
        
        public getAllUsersResponse(TestingWebServer.ServiceReference.getAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getAllUsersResponseBody() {
        }
        
        public getAllUsersResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllItems {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllItems", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getAllItemsBody Body;
        
        public getAllItems() {
        }
        
        public getAllItems(TestingWebServer.ServiceReference.getAllItemsBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllItemsBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getAllItemsBody() {
        }
        
        public getAllItemsBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllItemsResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getAllItemsResponseBody Body;
        
        public getAllItemsResponse() {
        }
        
        public getAllItemsResponse(TestingWebServer.ServiceReference.getAllItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getAllItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getAllItemsResponseBody() {
        }
        
        public getAllItemsResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTokenLifeTime", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class getTokenLifeTime {
        
        public getTokenLifeTime() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTokenLifeTimeResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class getTokenLifeTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public getTokenLifeTimeResponse() {
        }
        
        public getTokenLifeTimeResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateItem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateItem", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.updateItemBody Body;
        
        public updateItem() {
        }
        
        public updateItem(TestingWebServer.ServiceReference.updateItemBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateItemBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public updateItemBody() {
        }
        
        public updateItemBody(string arg0, int arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateItemResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.updateItemResponseBody Body;
        
        public updateItemResponse() {
        }
        
        public updateItemResponse(TestingWebServer.ServiceReference.updateItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class updateItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public updateItemResponseBody() {
        }
        
        public updateItemResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePassword {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePassword", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.changePasswordBody Body;
        
        public changePassword() {
        }
        
        public changePassword(TestingWebServer.ServiceReference.changePasswordBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class changePasswordBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public changePasswordBody() {
        }
        
        public changePasswordBody(string arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePasswordResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.changePasswordResponseBody Body;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(TestingWebServer.ServiceReference.changePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class changePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public changePasswordResponseBody() {
        }
        
        public changePasswordResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class login {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.loginBody Body;
        
        public login() {
        }
        
        public login(TestingWebServer.ServiceReference.loginBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public loginBody() {
        }
        
        public loginBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(TestingWebServer.ServiceReference.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logout {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.logoutBody Body;
        
        public logout() {
        }
        
        public logout(TestingWebServer.ServiceReference.logoutBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public logoutBody() {
        }
        
        public logoutBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(TestingWebServer.ServiceReference.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addItem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addItem", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.addItemBody Body;
        
        public addItem() {
        }
        
        public addItem(TestingWebServer.ServiceReference.addItemBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addItemBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public addItemBody() {
        }
        
        public addItemBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addItemResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.addItemResponseBody Body;
        
        public addItemResponse() {
        }
        
        public addItemResponse(TestingWebServer.ServiceReference.addItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class addItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public addItemResponseBody() {
        }
        
        public addItemResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteItem {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteItem", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.deleteItemBody Body;
        
        public deleteItem() {
        }
        
        public deleteItem(TestingWebServer.ServiceReference.deleteItemBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class deleteItemBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int arg1;
        
        public deleteItemBody() {
        }
        
        public deleteItemBody(string arg0, int arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="deleteItemResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.deleteItemResponseBody Body;
        
        public deleteItemResponse() {
        }
        
        public deleteItemResponse(TestingWebServer.ServiceReference.deleteItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class deleteItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public deleteItemResponseBody() {
        }
        
        public deleteItemResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUser", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.removeUserBody Body;
        
        public removeUser() {
        }
        
        public removeUser(TestingWebServer.ServiceReference.removeUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class removeUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public removeUserBody() {
        }
        
        public removeUserBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUserResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.removeUserResponseBody Body;
        
        public removeUserResponse() {
        }
        
        public removeUserResponse(TestingWebServer.ServiceReference.removeUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class removeUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public removeUserResponseBody() {
        }
        
        public removeUserResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUser", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.createUserBody Body;
        
        public createUser() {
        }
        
        public createUser(TestingWebServer.ServiceReference.createUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool arg3;
        
        public createUserBody() {
        }
        
        public createUserBody(string arg0, string arg1, string arg2, bool arg3) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createUserResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.createUserResponseBody Body;
        
        public createUserResponse() {
        }
        
        public createUserResponse(TestingWebServer.ServiceReference.createUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class createUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public createUserResponseBody() {
        }
        
        public createUserResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lockUser {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lockUser", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.lockUserBody Body;
        
        public lockUser() {
        }
        
        public lockUser(TestingWebServer.ServiceReference.lockUserBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class lockUserBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public lockUserBody() {
        }
        
        public lockUserBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lockUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lockUserResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.lockUserResponseBody Body;
        
        public lockUserResponse() {
        }
        
        public lockUserResponse(TestingWebServer.ServiceReference.lockUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class lockUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public lockUserResponseBody() {
        }
        
        public lockUserResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserName {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserName", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getUserNameBody Body;
        
        public getUserName() {
        }
        
        public getUserName(TestingWebServer.ServiceReference.getUserNameBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUserNameBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public getUserNameBody() {
        }
        
        public getUserNameBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUserNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUserNameResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.getUserNameResponseBody Body;
        
        public getUserNameResponse() {
        }
        
        public getUserNameResponse(TestingWebServer.ServiceReference.getUserNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class getUserNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public getUserNameResponseBody() {
        }
        
        public getUserNameResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCoolDownTime", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class getCoolDownTime {
        
        public getCoolDownTime() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCoolDownTimeResponse", WrapperNamespace="http://edu.softserve.com/", IsWrapped=true)]
    public partial class getCoolDownTimeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long @return;
        
        public getCoolDownTimeResponse() {
        }
        
        public getCoolDownTimeResponse(long @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unlockUsers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="unlockUsers", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.unlockUsersBody Body;
        
        public unlockUsers() {
        }
        
        public unlockUsers(TestingWebServer.ServiceReference.unlockUsersBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class unlockUsersBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public unlockUsersBody() {
        }
        
        public unlockUsersBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class unlockUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="unlockUsersResponse", Namespace="http://edu.softserve.com/", Order=0)]
        public TestingWebServer.ServiceReference.unlockUsersResponseBody Body;
        
        public unlockUsersResponse() {
        }
        
        public unlockUsersResponse(TestingWebServer.ServiceReference.unlockUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class unlockUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public unlockUsersResponseBody() {
        }
        
        public unlockUsersResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICommonChannel : TestingWebServer.ServiceReference.ICommon, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommonClient : System.ServiceModel.ClientBase<TestingWebServer.ServiceReference.ICommon>, TestingWebServer.ServiceReference.ICommon {
        
        public CommonClient() {
        }
        
        public CommonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CommonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CommonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.setCoolDownTimeResponse TestingWebServer.ServiceReference.ICommon.setCoolDownTime(TestingWebServer.ServiceReference.setCoolDownTime request) {
            return base.Channel.setCoolDownTime(request);
        }
        
        public bool setCoolDownTime(string arg0, long arg1) {
            TestingWebServer.ServiceReference.setCoolDownTime inValue = new TestingWebServer.ServiceReference.setCoolDownTime();
            inValue.Body = new TestingWebServer.ServiceReference.setCoolDownTimeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.setCoolDownTimeResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).setCoolDownTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setCoolDownTimeResponse> TestingWebServer.ServiceReference.ICommon.setCoolDownTimeAsync(TestingWebServer.ServiceReference.setCoolDownTime request) {
            return base.Channel.setCoolDownTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setCoolDownTimeResponse> setCoolDownTimeAsync(string arg0, long arg1) {
            TestingWebServer.ServiceReference.setCoolDownTime inValue = new TestingWebServer.ServiceReference.setCoolDownTime();
            inValue.Body = new TestingWebServer.ServiceReference.setCoolDownTimeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).setCoolDownTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.setTokenLifeTimeResponse TestingWebServer.ServiceReference.ICommon.setTokenLifeTime(TestingWebServer.ServiceReference.setTokenLifeTime request) {
            return base.Channel.setTokenLifeTime(request);
        }
        
        public bool setTokenLifeTime(string arg0, long arg1) {
            TestingWebServer.ServiceReference.setTokenLifeTime inValue = new TestingWebServer.ServiceReference.setTokenLifeTime();
            inValue.Body = new TestingWebServer.ServiceReference.setTokenLifeTimeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.setTokenLifeTimeResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).setTokenLifeTime(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setTokenLifeTimeResponse> TestingWebServer.ServiceReference.ICommon.setTokenLifeTimeAsync(TestingWebServer.ServiceReference.setTokenLifeTime request) {
            return base.Channel.setTokenLifeTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.setTokenLifeTimeResponse> setTokenLifeTimeAsync(string arg0, long arg1) {
            TestingWebServer.ServiceReference.setTokenLifeTime inValue = new TestingWebServer.ServiceReference.setTokenLifeTime();
            inValue.Body = new TestingWebServer.ServiceReference.setTokenLifeTimeBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).setTokenLifeTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.getAllUsersResponse TestingWebServer.ServiceReference.ICommon.getAllUsers(TestingWebServer.ServiceReference.getAllUsers request) {
            return base.Channel.getAllUsers(request);
        }
        
        public string getAllUsers(string arg0) {
            TestingWebServer.ServiceReference.getAllUsers inValue = new TestingWebServer.ServiceReference.getAllUsers();
            inValue.Body = new TestingWebServer.ServiceReference.getAllUsersBody();
            inValue.Body.arg0 = arg0;
            TestingWebServer.ServiceReference.getAllUsersResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).getAllUsers(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllUsersResponse> TestingWebServer.ServiceReference.ICommon.getAllUsersAsync(TestingWebServer.ServiceReference.getAllUsers request) {
            return base.Channel.getAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllUsersResponse> getAllUsersAsync(string arg0) {
            TestingWebServer.ServiceReference.getAllUsers inValue = new TestingWebServer.ServiceReference.getAllUsers();
            inValue.Body = new TestingWebServer.ServiceReference.getAllUsersBody();
            inValue.Body.arg0 = arg0;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).getAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.getAllItemsResponse TestingWebServer.ServiceReference.ICommon.getAllItems(TestingWebServer.ServiceReference.getAllItems request) {
            return base.Channel.getAllItems(request);
        }
        
        public string getAllItems(string arg0) {
            TestingWebServer.ServiceReference.getAllItems inValue = new TestingWebServer.ServiceReference.getAllItems();
            inValue.Body = new TestingWebServer.ServiceReference.getAllItemsBody();
            inValue.Body.arg0 = arg0;
            TestingWebServer.ServiceReference.getAllItemsResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).getAllItems(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllItemsResponse> TestingWebServer.ServiceReference.ICommon.getAllItemsAsync(TestingWebServer.ServiceReference.getAllItems request) {
            return base.Channel.getAllItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getAllItemsResponse> getAllItemsAsync(string arg0) {
            TestingWebServer.ServiceReference.getAllItems inValue = new TestingWebServer.ServiceReference.getAllItems();
            inValue.Body = new TestingWebServer.ServiceReference.getAllItemsBody();
            inValue.Body.arg0 = arg0;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).getAllItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.getTokenLifeTimeResponse TestingWebServer.ServiceReference.ICommon.getTokenLifeTime(TestingWebServer.ServiceReference.getTokenLifeTime request) {
            return base.Channel.getTokenLifeTime(request);
        }
        
        public long getTokenLifeTime() {
            TestingWebServer.ServiceReference.getTokenLifeTime inValue = new TestingWebServer.ServiceReference.getTokenLifeTime();
            TestingWebServer.ServiceReference.getTokenLifeTimeResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).getTokenLifeTime(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getTokenLifeTimeResponse> TestingWebServer.ServiceReference.ICommon.getTokenLifeTimeAsync(TestingWebServer.ServiceReference.getTokenLifeTime request) {
            return base.Channel.getTokenLifeTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getTokenLifeTimeResponse> getTokenLifeTimeAsync() {
            TestingWebServer.ServiceReference.getTokenLifeTime inValue = new TestingWebServer.ServiceReference.getTokenLifeTime();
            return ((TestingWebServer.ServiceReference.ICommon)(this)).getTokenLifeTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.updateItemResponse TestingWebServer.ServiceReference.ICommon.updateItem(TestingWebServer.ServiceReference.updateItem request) {
            return base.Channel.updateItem(request);
        }
        
        public bool updateItem(string arg0, int arg1, string arg2) {
            TestingWebServer.ServiceReference.updateItem inValue = new TestingWebServer.ServiceReference.updateItem();
            inValue.Body = new TestingWebServer.ServiceReference.updateItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            TestingWebServer.ServiceReference.updateItemResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).updateItem(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.updateItemResponse> TestingWebServer.ServiceReference.ICommon.updateItemAsync(TestingWebServer.ServiceReference.updateItem request) {
            return base.Channel.updateItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.updateItemResponse> updateItemAsync(string arg0, int arg1, string arg2) {
            TestingWebServer.ServiceReference.updateItem inValue = new TestingWebServer.ServiceReference.updateItem();
            inValue.Body = new TestingWebServer.ServiceReference.updateItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).updateItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.changePasswordResponse TestingWebServer.ServiceReference.ICommon.changePassword(TestingWebServer.ServiceReference.changePassword request) {
            return base.Channel.changePassword(request);
        }
        
        public bool changePassword(string arg0, string arg1, string arg2) {
            TestingWebServer.ServiceReference.changePassword inValue = new TestingWebServer.ServiceReference.changePassword();
            inValue.Body = new TestingWebServer.ServiceReference.changePasswordBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            TestingWebServer.ServiceReference.changePasswordResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).changePassword(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.changePasswordResponse> TestingWebServer.ServiceReference.ICommon.changePasswordAsync(TestingWebServer.ServiceReference.changePassword request) {
            return base.Channel.changePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.changePasswordResponse> changePasswordAsync(string arg0, string arg1, string arg2) {
            TestingWebServer.ServiceReference.changePassword inValue = new TestingWebServer.ServiceReference.changePassword();
            inValue.Body = new TestingWebServer.ServiceReference.changePasswordBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).changePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.loginResponse TestingWebServer.ServiceReference.ICommon.login(TestingWebServer.ServiceReference.login request) {
            return base.Channel.login(request);
        }
        
        public string login(string arg0, string arg1) {
            TestingWebServer.ServiceReference.login inValue = new TestingWebServer.ServiceReference.login();
            inValue.Body = new TestingWebServer.ServiceReference.loginBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.loginResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.loginResponse> TestingWebServer.ServiceReference.ICommon.loginAsync(TestingWebServer.ServiceReference.login request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.loginResponse> loginAsync(string arg0, string arg1) {
            TestingWebServer.ServiceReference.login inValue = new TestingWebServer.ServiceReference.login();
            inValue.Body = new TestingWebServer.ServiceReference.loginBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.logoutResponse TestingWebServer.ServiceReference.ICommon.logout(TestingWebServer.ServiceReference.logout request) {
            return base.Channel.logout(request);
        }
        
        public bool logout(string arg0, string arg1) {
            TestingWebServer.ServiceReference.logout inValue = new TestingWebServer.ServiceReference.logout();
            inValue.Body = new TestingWebServer.ServiceReference.logoutBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.logoutResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).logout(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.logoutResponse> TestingWebServer.ServiceReference.ICommon.logoutAsync(TestingWebServer.ServiceReference.logout request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.logoutResponse> logoutAsync(string arg0, string arg1) {
            TestingWebServer.ServiceReference.logout inValue = new TestingWebServer.ServiceReference.logout();
            inValue.Body = new TestingWebServer.ServiceReference.logoutBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.addItemResponse TestingWebServer.ServiceReference.ICommon.addItem(TestingWebServer.ServiceReference.addItem request) {
            return base.Channel.addItem(request);
        }
        
        public bool addItem(string arg0, string arg1) {
            TestingWebServer.ServiceReference.addItem inValue = new TestingWebServer.ServiceReference.addItem();
            inValue.Body = new TestingWebServer.ServiceReference.addItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.addItemResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).addItem(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.addItemResponse> TestingWebServer.ServiceReference.ICommon.addItemAsync(TestingWebServer.ServiceReference.addItem request) {
            return base.Channel.addItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.addItemResponse> addItemAsync(string arg0, string arg1) {
            TestingWebServer.ServiceReference.addItem inValue = new TestingWebServer.ServiceReference.addItem();
            inValue.Body = new TestingWebServer.ServiceReference.addItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).addItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.deleteItemResponse TestingWebServer.ServiceReference.ICommon.deleteItem(TestingWebServer.ServiceReference.deleteItem request) {
            return base.Channel.deleteItem(request);
        }
        
        public bool deleteItem(string arg0, int arg1) {
            TestingWebServer.ServiceReference.deleteItem inValue = new TestingWebServer.ServiceReference.deleteItem();
            inValue.Body = new TestingWebServer.ServiceReference.deleteItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.deleteItemResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).deleteItem(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.deleteItemResponse> TestingWebServer.ServiceReference.ICommon.deleteItemAsync(TestingWebServer.ServiceReference.deleteItem request) {
            return base.Channel.deleteItemAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.deleteItemResponse> deleteItemAsync(string arg0, int arg1) {
            TestingWebServer.ServiceReference.deleteItem inValue = new TestingWebServer.ServiceReference.deleteItem();
            inValue.Body = new TestingWebServer.ServiceReference.deleteItemBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).deleteItemAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.removeUserResponse TestingWebServer.ServiceReference.ICommon.removeUser(TestingWebServer.ServiceReference.removeUser request) {
            return base.Channel.removeUser(request);
        }
        
        public bool removeUser(string arg0, string arg1) {
            TestingWebServer.ServiceReference.removeUser inValue = new TestingWebServer.ServiceReference.removeUser();
            inValue.Body = new TestingWebServer.ServiceReference.removeUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.removeUserResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).removeUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.removeUserResponse> TestingWebServer.ServiceReference.ICommon.removeUserAsync(TestingWebServer.ServiceReference.removeUser request) {
            return base.Channel.removeUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.removeUserResponse> removeUserAsync(string arg0, string arg1) {
            TestingWebServer.ServiceReference.removeUser inValue = new TestingWebServer.ServiceReference.removeUser();
            inValue.Body = new TestingWebServer.ServiceReference.removeUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).removeUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.createUserResponse TestingWebServer.ServiceReference.ICommon.createUser(TestingWebServer.ServiceReference.createUser request) {
            return base.Channel.createUser(request);
        }
        
        public bool createUser(string arg0, string arg1, string arg2, bool arg3) {
            TestingWebServer.ServiceReference.createUser inValue = new TestingWebServer.ServiceReference.createUser();
            inValue.Body = new TestingWebServer.ServiceReference.createUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            TestingWebServer.ServiceReference.createUserResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).createUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.createUserResponse> TestingWebServer.ServiceReference.ICommon.createUserAsync(TestingWebServer.ServiceReference.createUser request) {
            return base.Channel.createUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.createUserResponse> createUserAsync(string arg0, string arg1, string arg2, bool arg3) {
            TestingWebServer.ServiceReference.createUser inValue = new TestingWebServer.ServiceReference.createUser();
            inValue.Body = new TestingWebServer.ServiceReference.createUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            inValue.Body.arg3 = arg3;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).createUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.lockUserResponse TestingWebServer.ServiceReference.ICommon.lockUser(TestingWebServer.ServiceReference.lockUser request) {
            return base.Channel.lockUser(request);
        }
        
        public bool lockUser(string arg0, string arg1) {
            TestingWebServer.ServiceReference.lockUser inValue = new TestingWebServer.ServiceReference.lockUser();
            inValue.Body = new TestingWebServer.ServiceReference.lockUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            TestingWebServer.ServiceReference.lockUserResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).lockUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.lockUserResponse> TestingWebServer.ServiceReference.ICommon.lockUserAsync(TestingWebServer.ServiceReference.lockUser request) {
            return base.Channel.lockUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.lockUserResponse> lockUserAsync(string arg0, string arg1) {
            TestingWebServer.ServiceReference.lockUser inValue = new TestingWebServer.ServiceReference.lockUser();
            inValue.Body = new TestingWebServer.ServiceReference.lockUserBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).lockUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.getUserNameResponse TestingWebServer.ServiceReference.ICommon.getUserName(TestingWebServer.ServiceReference.getUserName request) {
            return base.Channel.getUserName(request);
        }
        
        public string getUserName(string arg0) {
            TestingWebServer.ServiceReference.getUserName inValue = new TestingWebServer.ServiceReference.getUserName();
            inValue.Body = new TestingWebServer.ServiceReference.getUserNameBody();
            inValue.Body.arg0 = arg0;
            TestingWebServer.ServiceReference.getUserNameResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).getUserName(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getUserNameResponse> TestingWebServer.ServiceReference.ICommon.getUserNameAsync(TestingWebServer.ServiceReference.getUserName request) {
            return base.Channel.getUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getUserNameResponse> getUserNameAsync(string arg0) {
            TestingWebServer.ServiceReference.getUserName inValue = new TestingWebServer.ServiceReference.getUserName();
            inValue.Body = new TestingWebServer.ServiceReference.getUserNameBody();
            inValue.Body.arg0 = arg0;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).getUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.getCoolDownTimeResponse TestingWebServer.ServiceReference.ICommon.getCoolDownTime(TestingWebServer.ServiceReference.getCoolDownTime request) {
            return base.Channel.getCoolDownTime(request);
        }
        
        public long getCoolDownTime() {
            TestingWebServer.ServiceReference.getCoolDownTime inValue = new TestingWebServer.ServiceReference.getCoolDownTime();
            TestingWebServer.ServiceReference.getCoolDownTimeResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).getCoolDownTime(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getCoolDownTimeResponse> TestingWebServer.ServiceReference.ICommon.getCoolDownTimeAsync(TestingWebServer.ServiceReference.getCoolDownTime request) {
            return base.Channel.getCoolDownTimeAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.getCoolDownTimeResponse> getCoolDownTimeAsync() {
            TestingWebServer.ServiceReference.getCoolDownTime inValue = new TestingWebServer.ServiceReference.getCoolDownTime();
            return ((TestingWebServer.ServiceReference.ICommon)(this)).getCoolDownTimeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TestingWebServer.ServiceReference.unlockUsersResponse TestingWebServer.ServiceReference.ICommon.unlockUsers(TestingWebServer.ServiceReference.unlockUsers request) {
            return base.Channel.unlockUsers(request);
        }
        
        public bool unlockUsers(string arg0) {
            TestingWebServer.ServiceReference.unlockUsers inValue = new TestingWebServer.ServiceReference.unlockUsers();
            inValue.Body = new TestingWebServer.ServiceReference.unlockUsersBody();
            inValue.Body.arg0 = arg0;
            TestingWebServer.ServiceReference.unlockUsersResponse retVal = ((TestingWebServer.ServiceReference.ICommon)(this)).unlockUsers(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TestingWebServer.ServiceReference.unlockUsersResponse> TestingWebServer.ServiceReference.ICommon.unlockUsersAsync(TestingWebServer.ServiceReference.unlockUsers request) {
            return base.Channel.unlockUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<TestingWebServer.ServiceReference.unlockUsersResponse> unlockUsersAsync(string arg0) {
            TestingWebServer.ServiceReference.unlockUsers inValue = new TestingWebServer.ServiceReference.unlockUsers();
            inValue.Body = new TestingWebServer.ServiceReference.unlockUsersBody();
            inValue.Body.arg0 = arg0;
            return ((TestingWebServer.ServiceReference.ICommon)(this)).unlockUsersAsync(inValue);
        }
    }
}
